### PR TITLE
Support zsh tab completion in `twig init`

### PR DESCRIPTION
**Pull request by runcom**

### CODE REVIEW

**Comment by runcom** [comment]
I've submitted a pull request to `oh-my-zsh` project as well (https://github.com/robbyrussell/oh-my-zsh/pull/3653) in order to integrate Twig autocompletion as a plugin

**Comment by matteosister** [comment]
:+1: nice!

**Comment by rondevera** [comment]
@runcom Thanks for doing this—it looks great! As a quick update, I did a bunch of testing the past few nights, and will do some more this week before merging.

**Comment by runcom** [comment]
:+1: alright!

**Comment by rondevera** [comment]
@runcom Thanks again! This will be part of the v1.8 release.

**Comment by runcom** [comment]
@rondevera you're welcome!

**Pull request merged**
